contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
    # path('agenda/', views.agenda, name='agenda'),

    # contact (CRUD)
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# id (primary key - automático)
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)
# category (foreign key), show (boolean), picture (imagem)
# owner (foreign key)


# class Units(models.Model):
#     class Meta:
#         verbose_name = 'Unidade'

#     nome = models.CharField(max_length=50)

#     def __str__(self) -> str:
#         return self.nome


class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'

    nome = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nome


# class Category2(models.Model):
#     class Meta:
#         verbose_name = 'Uso do leito'
#         verbose_name_plural = 'Usos do leito'

#     nome = models.CharField(max_length=50)

#     def __str__(self) -> str:
#         return self.nome


class Contact(models.Model):
    class Meta:
        verbose_name = 'Agendamento'

    # unidade = models.ForeignKey(
    #     Units, on_delete=models.SET_NULL, blank=True, null=True)
    data_da_consulta = models.DateField(auto_now=False, blank=True, null=True)
    cpf = models.CharField(max_length=11, blank=True,
                           null=True, verbose_name='CPF')
    categoria = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True)
    nome_do_paciente = models.CharField(max_length=50, blank=True, null=True)
    hd = models.CharField(max_length=50, blank=True,
                          null=True, verbose_name='HD')
    telefone = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(
        max_length=254, blank=True, verbose_name='E-mail')
    anotacoes = models.TextField(blank=True, verbose_name='Anotações')
    show = models.BooleanField(default=True)
    # uso_do_leito = models.ForeignKey(
    #     Category2, on_delete=models.SET_NULL, blank=True, null=True)
    enviar_arquivo = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return f'{self.cpf} {self.hd} {self.nome_do_paciente}'

contact/forms.py
from django import forms
from contact.models import Contact
from django.shortcuts import render
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation


class ContactForm(forms.ModelForm):

    enviar_arquivo = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'img/*',
            }
        ),
        required=False
    )
    data_da_consulta = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'placeholder': 'dd/mm/aaaa',
            }
        ),
        required=False
    )

    class Meta:
        model = Contact
        fields = ('data_da_consulta', 'cpf', 'nome_do_paciente',
                  'hd', 'telefone', 'email', 'anotacoes', 'categoria',
                  'enviar_arquivo')

    def clean(self):
        cleaned_data = self.cleaned_data
        nome_do_paciente = cleaned_data.get('nome_do_paciente')
        hd = cleaned_data.get('hd')
        if nome_do_paciente == hd:
            msg = ValidationError(
                'O nome está igual ao hd',
                code='invalid'
            )
            self.add_error('nome_do_paciente', msg)
        return super().clean()


class RegisterForm(UserCreationForm):
    primeiro_nome = forms.CharField(
        required=True,
        min_length=3,
    )
    sobrenome = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'primeiro_nome', 'sobrenome', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )

        return email


class RegisterUpdateForm(forms.ModelForm):
    primeiro_nome = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Por favor, adicione mais que 2 letras'
        }
    )
    sobrenome = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'primeiro_nome', 'sobrenome', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

contact/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'contact/index.html')

contact/views/contact_forms.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from contact.forms import ContactForm
from contact.models import Contact


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):

    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(request, 'contact/contact.html',
                  {
                      'contact': contact,
                      'confirmation': confirmation,
                  }
                  )

contact/views/contact_views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from contact.models import Contact


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-data_da_consulta')

    paginator = Paginator(contacts, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }

    return render(request, 'contact/index.html', context)

# def agenda(request):
#     contacts = Contact.objects.filter(show=True).order_by('-id')[:10]

#     context = {'contacts': contacts,}

#     return render(request, 'contact/agenda.html', context)


def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    contact_name = f'{single_contact.nome_do_paciente} - '

    context = {
        'contact': single_contact,
        'site_title': contact_name
    }

    return render(request, 'contact/contact.html', context)


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects\
        .filter(show=True)\
        .filter(Q(nome_do_paciente__icontains=search_value) |
                Q(hd__icontains=search_value) |
                Q(data_da_consulta__icontains=search_value)) \
        .order_by('-id')

    paginator = Paginator(contacts, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Search - '
    }

    return render(request, 'contact/index.html', context)

contact/views/user_forms.py
from django.shortcuts import render, redirect
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


def register(request):

    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário registrado!')
            return redirect('contact:login')

    return render(
        request,
        'contact/register.html',
        {
            'form': form
        }
    )


@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form.save()
    return redirect('contact:user_update')


def login_view(request):

    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('contact:index')

        messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/login.html',
        {
            'form': form
        }
    )


@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

contact/templates/contact/agenda.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Agenda
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Data da consulta</th>
                    <th class="table-header">Nome do paciente</th>
                    <th class="table-header">CPF</th>
                    <th class="table-header">HD</th>
                    <th class="table-header">Telefone</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in contacts %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'contact:contact' contact.id %}">
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{contact.data_da_consulta}}
                        </td>
                        <td class="table-cel">
                            {{contact.nome_do_paciente}}
                        </td>
                        <td class="table-cel">
                            {{contact.cpf}}
                        </td>
                        <td class="table-cel">
                            {{contact.hd}}
                        </td>
                        <td class="table-cel">
                            {{contact.telefone}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.nome_do_paciente}}
        </h1>
        <p><b>ID:</b> {{contact.id}}</p>
        <p><b>Data da consulta:</b> {{contact.data_da_consulta}}</p>
        <p><b>CPF:</b> {{contact.cpf}}</p>
        <p><b>HD:</b> {{contact.hd}}</p>
        <p><b>Telefone:</b> {{contact.telefone}}</p>
        <p><b>Email:</b> {{contact.email}}</p>
        <p><b>Anotações:</b> {{contact.anotacoes}}</p>
        <p><b>Data da criação:</b> {{contact.created_date}}</p>
        <p><b>Categoria:</b> {{contact.categoria.nome}}</p>

        {% if contact.enviar_arquivo %}
            <p>
                <img src="{{ contact.enviar_arquivo.url }}" alt="{{ contact.nome_do_paciente }}">
            </p>
        {% endif %}


        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Atualizar</a>

            <form action="{% url 'contact:delete' contact.id %}" method="POST">

                {% csrf_token %}

                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes"> 
                    <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
                {% else %}
                    <button class="btn btn-link btn-delete" type="submit">Excluir</button>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}
{% block content %}
  <div class="form-wrapper">
    <h2>Criar agendamento</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}      
      
      <div class="form-content">
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>

          {% if field.name == 'enviar_arquivo' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}
      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Agenda
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Data da consulta</th>
                    <th class="table-header">Nome do paciente</th>
                    <th class="table-header">CPF</th>
                    <th class="table-header">HD</th>
                    <th class="table-header">Telefone</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'contact:contact' contact.id %}">
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{contact.data_da_consulta|date:"d-m-Y"}}
                        </td>
                        <td class="table-cel">
                            {{contact.nome_do_paciente}}
                        </td>
                        <td class="table-cel">
                            {{contact.cpf}}
                        </td>
                        <td class="table-cel">
                            {{contact.hd}}
                        </td>
                        <td class="table-cel">
                            {{contact.telefone}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <div class="single-contact">
        <h1 class="single-contact-name-search">
            Nenhuma informação encontrada.
        </h1>
    </div>
{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Login </h2>

    {% if user.is_authenticated %}
      <p>
        Você está logado como {{ user.username }}.
        Clique <a href="{% url 'contact:logout' %}">aqui</a>
        para sair.
      </p>
    {% else %}
      {% include 'contact/partials/_user-form.html' %}
    {% endif %}
  </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Registrando novo usuário</h2>

    {% include 'contact/partials/_user-form.html' %}
    
  </div>
{% endblock content %}

contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Atualizar dados do usuário</h2>

    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}